apiVersion: v1
kind: ServiceAccount
metadata:
    annotations:
        kubernetes.io/enforce-mountable-secrets: "true"
    name: vault
    namespace: vault-k3s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: vault-k3s
    name: vault
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
apiVersion: app/v1
kind: Deployment
metadata:
    name: vault
    namespace: vault-k3s
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault"
        vault.hashicorp.com/agent-inject-token: "true"
    spec: 
      serviceAccountName: vault
      containers:
      - name: vault-k3s-agent-injector-7f5cd64c6d-h6lmm
        image: "hashicorp/vault:latest"
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault-k3s.svc.cluster.local:8200"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        volumeMounts:
        - name: vault-agent-config
          mountPath: /etc/vault-agent.d
      volumes:
      - name: vault-agent-config
        configMap:
          name: vault-agent-config
